=== Cheng17415/XSD/11_inventario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="inventario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="codigo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="COD-\d{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="codigo_inverso" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{3}-DOC"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="nombre" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="categoria">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="ElectrÃ³nica"/>
                                    <xs:enumeration value="Hogar"/>
                                    <xs:enumeration value="Deportes"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Cheng17415/XSD/11_inventario.xml
<?xml version="1.0" encoding="UTF-8"?> 
<inventario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="11_inventario.xsd"> 
  <producto categoria="Electrónica"> 
     <codigo>COD-001</codigo> 
     <nombre>Smartphone XYZ</nombre> 
  </producto> 
  <producto categoria="Hogar"> 
     <codigo>COD-002</codigo> 
     <nombre>Aspiradora</nombre> 
  </producto> 
  <producto categoria="Deportes"> 
     <codigo>COD-003</codigo> 
     <nombre>Zapatillas</nombre> 
  </producto> 
  <producto categoria="Electrónica"> 
    <codigo>COD-001</codigo> 
    <codigo_inverso>100-DOC</codigo_inverso> 
    <nombre>Smartphone XYZ</nombre> 
  </producto>  
</inventario>
